// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcsmufazonpniprdgsqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc211ZmF6b25wbmlwcmRnc3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDA3ODUsImV4cCI6MjA2OTcxNjc4NX0.-ncliyDEh4gUZc-IMjj_OLMWEnS_ZVDwrj1JWrlf0Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});